[package]
name = "fetch"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
arcstr = "1.2.0"
global-hotkey = "0.7.0"
gpui = "0.2.0"
gpui-component = "0.4.0-preview1"
open = "5.3.2"
rayon = "1.11.0"
scc = "3.3.7"
unicase = "2.8.1"
unicode-segmentation = "1.12.0"

[lints] 
clippy = { pedantic = "deny" }

[package.metadata.bundle]
name = "Fetch"
identifier = "org.birds.fetch"
version = "0.0.1"
category = "Developer Tool"
short_description = "No-bullshit app launcher."